Change CONFIDENCE_ASSESSMENT from a THING to an ENTITY.
A confidence assessment is something which exists, and is therefore reasonable to
be an entity.

In addition, it has a wasGeneratedBy property that is not defined for THING but
which is defined for ENTITY.  This issue was detected by ASSIST-DV with the
enhancements in PR#782 with the following report:

> ERROR: Property http://arcos.rack/PROV-S#wasGeneratedBy was referenced on class http://arcos.rack/CONFIDENCE#CONFIDENCE_ASSESSMENT, but that property is only defined for the unrelated class http://arcos.rack/PROV-S#ENTITY